# Generated by Django 4.1.13 on 2025-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('in_topic', models.CharField(max_length=255)),
                ('out_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField()),
                ('qos', models.IntegerField()),
                ('time_ms', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
