# Generated by Django 4.2.27 on 2025-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttmiddleware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(help_text="e.g. 'temp' or 'hum'", max_length=50, unique=True)),
                ('threshold', models.FloatField(default=20.0)),
            ],
        ),
    ]
